### ISSUE TITLE
About DOCUMENTATION.md

### ISSUE THREAD

**Issue by glaukiol1** [glaukiol1/document.js#10]
@marcotduenas, i see there are two other files, namely; 
```
.DOCUMENTATION.md.un~ 

DOCUMENTATION.md~ 
```
Can you please tell me if we still need these files? I will be looking to delete them but id like to ask you first. Thanks!

**Comment by marcotduenas** [comment]
I think that's from Vim, you can delete it :)

**Comment by glaukiol1** [comment]
Thanks for the response! I will delete it.
