### ISSUE TITLE
Fix Documentation (Easy)

### ISSUE THREAD

**Issue by glaukiol1** [glaukiol1/document.js#2]
This is a very easy thing to make, fix up the `/DOCUMENT.md` file, make it look better!

**Comment by marcotduenas** [comment]
Can you give me more details?

**Comment by glaukiol1** [comment]
@marcotduenas, of course. In the main directory, there is a file called DOCUMENTATION.md, in that file is the documentation for all of the functions that document.js provides. I would really like someone to neatly remake that document, so its easier to read. If you have any question, please don't hesitate to ask! Thanks!

**Comment by glaukiol1** [comment]
You first need to fork this project, after that make your changes, and submit a pull request! Thanks

**Comment by glaukiol1** [comment]
You can also work on the README, if you would like

**Comment by glaukiol1** [comment]
I renamed all of the functions to the below; the left is the old name and the right is the new name. You can rename them in DOCUMENTAION.md and it will be a very good contribution. Also, if you dont really know how to contribute, go [here](https://github.com/glaukiol1/easy-contributions-for-first-time), it is a full guide on how to contribute in GitHub. After you are ready, you can use the data below to fix the DOCUMENTATION.md file! 
```py
addDOMElememtNoParams = newElement
addDOMElememtWithID = newElementWithId
addDOMElememtWithClass = newElementWithClass
addDOMElememtWithIdAndClass = newElementWithIdAndClass
h1HeadingWithIDandClass  = h1WithIdAndClass
h1HeadingWithID = h1WithId
h1HeadingWithNoParams = h1
h1HeadingWithClass = h1WithClass
h2HeadingWithIDandClass = h2WithIdAndClass
h2HeadingWithID = h2WithId
h2HeadingWithNoParams = h2
h2HeadingWithClass = h2WithClass
h3HeadingWithIDandClass = h3WithIdAndClass
h3HeadingWithID = h3WithId
h3HeadingWithNoParams = h3
h3HeadingWithClass = h3WithClass
h4HeadingWithIDandClass = h4WithIdAndClass
h4HeadingWithID = h4WithId
h4HeadingWithNoParams = h4
h4HeadingWithClass = h4WithClass
paragraphWithIDandClass = pWithIdAndClass
paragraphWithID = pWithId
paragraphWithNoParams = p
```
