### ISSUE TITLE
Fix the DOCUMENTATION.md file for the new function names!

### ISSUE THREAD

**Issue by glaukiol1** [glaukiol1/document.js#4]
I recently edited the module, so the function names are different now. Below you have a list of the renamed functions;
| Old function name | New Function Name |
| ---------------------------------- | -------------------- | 
|addDOMElememtNoParams | newElement  |
|addDOMElememtWithID | newElementWithId |
|addDOMElememtWithClass | newElementWithClass |
|addDOMElememtWithIdAndClass | newElementWithIdAndClass |
|h1HeadingWithIDandClass  | h1WithIdAndClass |
|h1HeadingWithID | h1WithId |
|h1HeadingWithNoParams | h1 |
|h1HeadingWithClass | h1WithClass |
|h2HeadingWithIDandClass | h2WithIdAndClass |
|h2HeadingWithID | h2WithId |
|h2HeadingWithNoParams | h2 |
|h2HeadingWithClass | h2WithClass |
|h3HeadingWithIDandClass | h3WithIdAndClass |
|h3HeadingWithID | h3WithId |
|h3HeadingWithNoParams | h3 |
|h3HeadingWithClass | h3WithClass |
|h4HeadingWithIDandClass | h4WithIdAndClass |
|h4HeadingWithID | h4WithId |
|h4HeadingWithNoParams | h4 |
|h4HeadingWithClass | h4WithClass |
|paragraphWithIDandClass | pWithIdAndClass |
|paragraphWithID | pWithId |
|paragraphWithNoParams | p |

Thanks for contributing to document.js!

**Comment by Abhishekbharti9910** [comment]
how i can contribute to this issue, I am new to opensource and this is my first contribution. can you guide me little bit

**Comment by glaukiol1** [comment]
Of course, so first, you need to fork this repo. I see you have already done that, so good job. Then, in your computer, clone YOUR fork of document.js, the url is https://github.com/yourusernamehere/document.js
Make sure you replace yourusernamehere with your real username. Now, in the command line, run;
`git clone https://github.com/username/document.js`
Replace username with your real username. After, make your changes, and run the following commands
```
git add .
git commit -m "description here"
git push
```
After that, go to your fork on github.com, and you should see a button saying "main had recent pushes, pull request?" Click on the green button, and it will take you to another page, here, click the green button again. Now, fill in the description of what you did, and press submit pull request! Thanks for contributing! If you have any questions, don't hesitate to ask.

**Comment by glaukiol1** [comment]
You can make whatever changes you want, if you want to fix some stuff in the README.md file, or the DOCUMENTATION.md, its fine! If you want to help with the code itself, youre welcome!

**Comment by glaukiol1** [comment]
If you have any other questions, please open a new issue

**Comment by glaukiol1** [comment]
Thanks to @Atkinstinkmoore for fixing this!
