### ISSUE TITLE
document.js README Fixes (Easy)

### ISSUE THREAD

**Issue by glaukiol1** [glaukiol1/document.js#7]
# document.js README Fixes (Easy)

Anyone can help to develop document.js! If you want a small thing to do, this is the one for you! You can make some small fixes and additions to the docs, and the README. Reply to this issue if you want to do this! There is a guide on contributing in CONTRIBUTING.md, thanks!

---

Make sure to star this repo if you like it!

**Comment by Akhil132-dev** [comment]
yes  i want to contribute in this
